### ISSUE TITLE
Connection Refused Error with script

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit_client#2]
@bloodstalker getting this error when I try to use your script:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Transport("Io(Error { repr: Os { code: 61, message: \"Connection refused\" } })")', src/libcore/result.rs:860:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_new
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <core::result::Result<T, E>>::unwrap
  10: truebit_client::main
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start
  13: main
killing parity...
./run.sh: line 29: kill: (2230) - No such process
```

**Comment by bloodstalker** [comment]
could you please check and see whether parity was ran successfully?
kill complains there is no such process which means parity isnt up which explains why rust would raise a panic.
run the parity command from script in the terminal and see what it complains about.
lemme know.

**Comment by hswick** [comment]
When using script with parity already running I get this:
```
Balance: 0xfffffffffffffffffffffffffffffffffffffbdaabb8947f00
0x1f79…c6f4
0x0
0x2a
killing parity...
./run.sh: line 29: kill: (2738) - No such process
```

Which was successful, but the kill didn't work.

When running script with parity not already running it gives the error I initially posted.

**Comment by bloodstalker** [comment]
kill wont work since $PID will be null if we dont run parity from script.
could you please run this and tell me what it returns:
parity --chain dev --unlock 0x00a329c0648769a73afac7f9381e08fb43dbea72 --password ./password.txt &

**Comment by hswick** [comment]
Yeah that worked, just the output from the Rust code. No error.

**Comment by hswick** [comment]
Was able to actually kill the parity daemon with:
`lsof -t -i tcp:8545 | xargs kill`

**Comment by bloodstalker** [comment]
the kill wont work in the script since the parity launch is not successful from inside the script.
replace the parity run command in the script with: 
`parity --chain dev --unlock 0x00a329c0648769a73afac7f9381e08fb43dbea72 --password ./password.txt &`
see if that helps.

**Comment by hswick** [comment]
It couldn't find the parity command for some reason...
```
building the solidity contracts...
running parity:...
parity's up...
running truebit client...
./run.sh: line 18: parity: command not found
   Compiling truebit_client v0.0.1 (file:///Users/guattari/projects/truebit/truebit_client)
warning: unused import: `Address`
 --> src/main.rs:6:19
  |
6 | use web3::types::{Address, U256};
  |                   ^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 4.61 secs
     Running `target/debug/truebit_client`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Transport("Io(Error { repr: Os { code: 61, message: \"Connection refused\" } })")', src/libcore/result.rs:860:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_new
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <core::result::Result<T, E>>::unwrap
  10: truebit_client::main
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start
  13: main
killing parity...
./run.sh: line 29: kill: (6942) - No such process
```

**Comment by bloodstalker** [comment]
weird. isn't parity in bash's path?
which shell is your terminal running|?

**Comment by bloodstalker** [comment]
also one source of problem could be that your shell is  suspending parity when we run it as a background process.
run `stty tostop` once and then try to run the script.

**Comment by hswick** [comment]
oops forgot I setup parity as an alias haha
`alias parity="/Applications/Parity\ Ethereum.app/Contents/MacOS/parity"`

How do I add parity to my path?

**Comment by bloodstalker** [comment]
this is mine in my .zshrc:
`export PATH=:$PATH:/home/bloodstalker/extra/parity/target/release`
